repos:
- hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
  repo: meta
- hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - files: ^.pre-commit-config.yaml$
    id: check-yaml
    name: Check pre-commit config
  repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - id: nixpkgs-fmt
    name: Format .nix files
  repo: git://github.com/nix-community/nixpkgs-fmt
  rev: v1.0.0
