repos:
- hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
  repo: meta
- hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- hooks:
  - id: nixpkgs-fmt
    name: Format .nix files
  repo: git://github.com/nix-community/nixpkgs-fmt
  rev: v0.9.0
