[package]
name = "yurrriq/gis"
version = "0.4.1"
authors = ["Eric Bailey <eric@ericb.me>"]
repository = "https://github.com/yurrriq/gis"
# TODO: readme = "README.md"
license = "MIT"

[dev_dependencies]
[dev_dependencies."pheymann/specdris"]
git = "https://github.com/pheymann/specdris"
tag = "v0.3.1"

[targets.lib]
path = "src/"
mods = [
  "Data.GIS",
  "Data.GIS.Verified",
  "Data.Int.Algebra",
  "Data.Music",
]
idris_opts = ["-p", "contrib"]

[[targets.test]]
path = "test/"
main = "Data.GIS.Test.runTests"
idris_opts = ["-p", "contrib", "-p", "specdris"]

[[targets.test]]
path = "test/"
main = "Data.Music.Test.runTests"
idris_opts = ["-p", "contrib", "-p", "specdris"]
